export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST"
export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS"
export const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL"

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST"
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS"
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAILS_FAIL"

export const TV_DETAILS_REQUEST = "TV_DETAILS_REQUEST"
export const TV_DETAILS_SUCCESS = "TV_DETAILS_SUCCESS"
export const TV_DETAILS_FAIL = "TV_DETAILS_FAIL"

export const MOVIE_GENRES_SUCCESS = "MOVIE_GENRES_SUCCESS"
export const MOVIE_GENRES_FAIL = "MOVIE_GENRES_FAIL"
